{
 "title": "New dashboard",
 "time": { "from": "2024-02-28T13:09:34.925Z", "to": "2024-03-28T05:50:30.933Z" },
 "panels": [
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM nyc_prediction_model_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT share_missing_values, \"timestamp\" FROM nyc_prediction_model_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_columns, \"timestamp\" FROM nyc_prediction_model_metrics LIMIT 50 "
    }
   ]
  }
 ]
}